steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/notes-backend', '.']
    dir: 'notes-backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notes-backend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'notes-backend',
        '--image', 'gcr.io/$PROJECT_ID/notes-backend',
        '--region', 'us-central1',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
